# Generated by Django 6.1 on 2026-09-23 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('sinopse', models.CharField(blank=True, max_length=1000)),
                ('editora', models.CharField(max_length=200)),
                ('generos', models.CharField(blank=True, max_length=90)),
                ('ano', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)])),
                ('status', models.CharField(choices=[('disponível', 'Disponível'), ('reservado', 'Reservado'), ('emprestado', 'Emprestado'), ('indisponivel', 'Indisponível')], default='disponível', max_length=20)),
                ('capa', models.ImageField(blank=True, upload_to='capas/')),
            ],
        ),
    ]
