# Generated by Django 6.1 on 2026-09-30 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='sinopse',
            new_name='descricao',
        ),
        migrations.AddField(
            model_name='livro',
            name='numero_paginas',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='CDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=200)),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subclasses', to='livros.cdd')),
            ],
        ),
        migrations.AddField(
            model_name='livro',
            name='cdd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='livros.cdd'),
        ),
    ]
