# Generated by Django 6.1 on 2026-09-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_inserir_cdds'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='isbn',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
    ]
