# Generated by Django 6.1 on 2026-09-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0006_delete_bibliotecario_delete_leitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='livro',
            name='genero',
        ),
        migrations.AddField(
            model_name='livro',
            name='_status',
            field=models.CharField(choices=[('disponível', 'Disponível'), ('reservado', 'Reservado'), ('emprestado', 'Emprestado'), ('indisponivel', 'Indisponível')], default='disponível', max_length=20),
        ),
        migrations.AddField(
            model_name='livro',
            name='generos',
            field=models.ManyToManyField(to='livros.genero'),
        ),
    ]
