# Generated by Django 6.1 on 2026-09-16 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0007_genero_remove_livro_genero_livro__status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='_status',
            new_name='status',
        ),
    ]
