# Generated by Django 6.1 on 2026-09-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_pedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
